
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";

import App from "./pages/App";
import Calendar from "./pages/Calendar";
import CreateRequest from "./pages/CreateRequest";
import Dashboard from "./pages/Dashboard";

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/calendar", element: <Calendar />},
	{ path: "/create-request", element: <CreateRequest />},
	{ path: "/createrequest", element: <CreateRequest />},
	{ path: "/dashboard", element: <Dashboard />},

];
