
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const Calendar = lazy(() => import("./pages/Calendar.tsx"));
const CreateRequest = lazy(() => import("./pages/CreateRequest.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/calendar", element: <Calendar />},
	{ path: "/create-request", element: <CreateRequest />},
	{ path: "/createrequest", element: <CreateRequest />},
	{ path: "/dashboard", element: <Dashboard />},

];
